workspaces := "./packages ./contracts "

# Displays available recipes by running `just -l`.
setup:
  #!/usr/bin/env bash
  just -l

install:
  # https://crates.io/crates/clippy
  rustup component add clippy
  # https://crates.io/crates/cargo-llvm-cov
  cargo install cargo-llvm-cov

wasm-all:
  bash scripts/wasm-out.sh

# Move binding artifacts to teh local nibiru wasmbin
wasm-export:
  bash scripts/wasm-export.sh

# Compiles a single CW contract to wasm bytecode.
# wasm-single:
#   bash scripts/wasm-out.sh --single

# Runs rustfmt
fmt:
  cargo fmt --all

# Runs rustfmt without updating
fmt-check:
  cargo fmt --all -- --check

# Compiles Rust code
build:
  cargo build

build-update:
  cargo update
  cargo build

# Clean target files and temp files
clean:
  cargo clean

# Run linter + fix
clippy:
  cargo clippy --fix --allow-dirty --allow-staged

# Run linter + check only
clippy-check:
  cargo clippy

# Test a specific package or contract
test *pkg:
  #!/usr/bin/env bash
  set -e;
  if [ -z "{{pkg}}" ]; then
    just test-all
  else
    RUST_BACKGTRACE="1" cargo test --package "{{pkg}}"
  fi

# Test everything in the workspace.
test-all:
  cargo test

# Test everything and output coverage report.
test-coverage:
  cargo llvm-cov --lcov --output-path lcov.info \
    --ignore-filename-regex .*buf\/[^\/]+\.rs$

# Format, lint, and test
tidy:
  just fmt
  just clippy
  just test

# Format, lint, update dependencies, and test
tidy-update: build-update
  just tidy

# Run local instance of the Nibiru blockchain
run-nibiru:
  bash scripts/localnet.sh --no-build

run-pricefeed:
  bash scripts/run_pricefeed.sh

# Install wasm target, nibid, and pricefeeder
install-everything:
  rustup target add wasm32-unknown-unknown
  curl -s https://get.nibiru.fi/! | bash
  curl -s https://get.nibiru.fi/pricefeeder! | bash

add-key:
  #!/usr/bin/env bash
  export KEY_NAME="test-me"
  add_key() {
    MNEM="guard cream sadness conduct invite crumble clock pudding hole grit liar hotel maid produce squeeze return argue turtle know drive eight casino maze host" 
    echo "$MNEM" | nibid keys add $KEY_NAME --recover --keyring-backend test
  }
  add_key 2> /dev/null
  nibid keys list | jq

# Set up keys and environment variables for nibid
setup-env:
  #!/usr/bin/env bash
  source scripts/setup_env.sh
  echo "WASM: $WASM"
  echo "KEY_NAME: $KEY_NAME"
